apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ehrnu5bzq-nodejs
  janus-idp.io/tekton: ehrnu5bzq-nodejs
  backstage.io/kubernetes-id: ehrnu5bzq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ehrnu5bzq-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
