apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ehrnu5bzq-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-bdecee23ad.2jb9.p3.openshiftapps.com/rhtap/rhtap-qe:281d0096714245c2d9f69a6d10803e7b764f35f9@sha256:446c3a734fd7dcafecd4557b327b673731c1870dffef5ea1aa5b72d4440c2b83
          name: container-image
